name: master-ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .net core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.106

      - name: Build solution
        run: dotnet build --configuration Release
        working-directory: ./src

      - name: Run tests
        run: dotnet test --configuration Release
        working-directory: ./src

      - name: Show version
        run: |
          git symbolic-ref --quiet --short HEAD 2>/dev/null
          git rev-list --count HEAD
